### ISSUE TITLE
NanoMQ bridge cannot connect to EMQX Serverless due to missing SNI support

### ISSUE THREAD

**Issue by Fllorent0D** [nanomq/nanomq#2135]
Description:
I encountered an issue where my NanoMQ bridge setup works fine on EMQX Dedicated, but fails on EMQX Serverless.
After opening a support ticket with EMQX, I was informed that:
- NanoMQ does not currently support setting SNI (Server Name Indication) in the TLS handshake.
- EMQX Serverless requires SNI to correctly route clients between tenants.
- EMQX Dedicated does not require SNI, which is why the bridge works there.

This means that at the moment, NanoMQ cannot connect to EMQX Serverless over TLS.

Steps to reproduce:
- Configure a NanoMQ bridge to an EMQX Serverless deployment with TLS enabled.
- Observe that the connection fails during the TLS handshake.
- Configure the same bridge to an EMQX Dedicated deployment → works fine.

Expected behavior:
NanoMQ should allow setting an SNI hostname in the TLS handshake so it can connect to SNI-required brokers (such as EMQX Serverless).

Actual behavior:
TLS handshake fails because no SNI is sent.

Questions:
- Is there a known workaround (e.g., patch, custom build, config flag) to enable SNI in NanoMQ?
- Are there plans to add SNI support in the near future?

**Comment by StillNotUsefull** [comment]
I have the exact same problem. I have an EMQX Broker running behind an HA-Proxy. I do not terminate the TLS on the HA-Proxy and i use the SNI to route to the corresponding backend. 

My local Nanomq instance can not connect and its just looping in a reconnect.

**Comment by JaylinYu** [comment]
done

**Comment by StillNotUsefull** [comment]
Hi @JaylinYu,

i tested the beta image today morning: nanomq-0.24.4-sdv.beta.2-linux-amd64-sdv.tar.gz

Has this change been included to this image. If yes than the same issue is still present.

**Comment by JaylinYu** [comment]
@Jooonnnaass 
I haven't released any tag after this PR. Where did you find such a release tar with a suffix name "SDV" ... pretty curious.
You can try compiling from source to verify this first.

**Comment by StillNotUsefull** [comment]
@JaylinYu It got released on this repository today. I subscribed to the release notification because i need this change asap. It got tagged with "0.24.4-sdv.beta.2" based on commit "bfe0935. Its really strage because the release is now deleted :P

**Comment by JaylinYu** [comment]
ok got it. That was a wrong click by one of our men.
I can confirm the tag you tried didnt include this PR.
